name: publish release

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - runs: python -m build
      - uses: pypa/gh-action-pypi-publish@v1.8.3
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
